---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- path: exampleSite/content
  label: Pages
  create: all
- path: exampleSite/content/work
  label: Work
  create: all
upload_dir: exampleSite/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
